name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract project
        run: |
          # Распаковываем то, что прислал твой Python-скрипт
          unzip -o project.zip -d .
          ls -R # Посмотрим в логах, что внутри

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git libssl-dev libffi-dev python3-dev libgimpprint-dev
          pip3 install --user --upgrade buildozer Cython==0.29.33

      - name: Create spec if not exists
        run: |
          # Если файла настроек нет, создаем его на лету
          if [ ! -f buildozer.spec ]; then
            buildozer init
            sed -i 's/package.name = myapp/package.name = lopuhapp/' buildozer.spec
            sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,html,css,js/' buildozer.spec
          fi

      - name: Build with Buildozer
        run: |
          # Собираем APK
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: LOPUH_READY_APK
          path: bin/*.apk
